import React, { useState, useRef, useMemo } from "react";
import {
  CADDrawingRecord,
  CADCategory,
  CADFileType,
  CADAttachment,
  CADFolder
} from "../../../types/dataStorageTypes";
import {
  saveCADDrawingRecord,
  getStoredCADFolders,
  formatBytes
} from "../../../utils/dataStorageManager";
import {
  X,
  Save,
  Upload,
  FileText,
  FileCode,
  Tag,
  Plus,
  Trash2,
  Paperclip,
  Check,
  Building,
  User,
  Phone,
  MapPin,
  Sparkles,
  Layers,
  FolderKanban,
  Star,
  Compass,
  Home,
  Folder,
  Ruler,
  AlertCircle
} from "lucide-react";

interface CadFileEditModalProps {
  file: CADDrawingRecord | null;
  defaultFolderId?: string | null;
  defaultCategory?: CADCategory;
  isOpen: boolean;
  onClose: () => void;
  onSaved: (savedFile: CADDrawingRecord) => void;
  onDelete?: (fileId: string) => void;
  userEmail: string;
}

const CATEGORIES: { value: CADCategory; label: string; labelMl: string }[] = [
  { value: "PLAN", label: "1. PLAN", labelMl: "പ്ലാൻ (Architectural, Vastu & 2D CAD)" },
  { value: "3D", label: "2. 3D", labelMl: "3D എലിവേഷൻ & വിഷ്വലൈസേഷൻ" },
  { value: "ESTIMATE", label: "3. ESTIMATE", labelMl: "എസ്റ്റിമേറ്റ് & BOQ" },
  { value: "SURVEY", label: "4. SURVEY", labelMl: "ലാൻഡ് സർവ്വേ & FMB" },
  { value: "DOCUMENTS", label: "5. DOCUMENTS", labelMl: "ഓഫീസ് ഡോക്യുമെന്റുകൾ & പെർമിറ്റുകൾ" }
];

const FACING_OPTIONS = [
  "East (കിഴക്ക്)",
  "West (പടിഞ്ഞാറ്)",
  "North (വടക്ക്)",
  "South (തെക്ക്)",
  "North-East (ഈശാനകോൺ)",
  "North-West (വായുകോൺ)",
  "South-East (അഗ്നികോൺ)",
  "South-West (നിര്യതികോൺ)"
];

const BEDROOM_OPTIONS = [
  "1 BHK",
  "2 BHK",
  "3 BHK",
  "4 BHK",
  "5+ BHK",
  "Commercial / Office (N/A)"
];

const FLOOR_OPTIONS = [
  "Single Floor (Ground Floor)",
  "G + 1 (2 Floors)",
  "G + 2 (3 Floors)",
  "G + 3 (4 Floors)",
  "Multi-Storey Tower"
];

const SUGGESTED_KEYWORDS = [
  "3bhk",
  "2bhk",
  "4bhk",
  "east entry",
  "north entry",
  "pooja room",
  "brahmasthanam",
  "vastu compliant",
  "keralassery",
  "palakkad",
  "ksmart",
  "lsgd permit",
  "kpbr 2019",
  "kpbr 2024",
  "column layout",
  "footing schedule",
  "dwg",
  "dxf",
  "pdf",
  "3d elevation"
];

export const CadFileEditModal: React.FC<CadFileEditModalProps> = ({
  file,
  defaultFolderId,
  defaultCategory,
  isOpen,
  onClose,
  onSaved,
  onDelete,
  userEmail
}) => {
  const fileInputRef = useRef<HTMLInputElement | null>(null);
  const folders = getStoredCADFolders();

  const [folderId, setFolderId] = useState<string>(
    file?.folderId || defaultFolderId || "folder-deepak"
  );
  const [name, setName] = useState(file?.name || "");
  const [projectCode, setProjectCode] = useState(file?.projectCode || "");
  
  // Client & Architectural Details
  const [ownerName, setOwnerName] = useState(file?.ownerName || file?.clientName || "");
  const [mobileNo, setMobileNo] = useState(file?.mobileNo || file?.clientPhone || "");
  const [facing, setFacing] = useState(file?.facing || "East (കിഴക്ക്)");
  const [bedrooms, setBedrooms] = useState(file?.bedrooms || "3 BHK");
  const [floors, setFloors] = useState(file?.floors || "Single Floor (Ground Floor)");
  const [vasthuChuttu, setVasthuChuttu] = useState(file?.vasthuChuttu || "43 Kol 16 Viral (Dhana Porutham)");
  const [builtUpArea, setBuiltUpArea] = useState(file?.builtUpArea || "1650 Sq.Ft (153.3 Sq.M)");
  const [location, setLocation] = useState(file?.location || "Keralassery, Palakkad");
  
  const [category, setCategory] = useState<CADCategory>(file?.category || defaultCategory || "PLAN");
  const [fileType, setFileType] = useState<CADFileType>(file?.fileType || "DWG");
  const [description, setDescription] = useState(file?.description || "");
  const [isStarred, setIsStarred] = useState(file?.isStarred || false);

  // Attachments State
  const [attachments, setAttachments] = useState<CADAttachment[]>(file?.attachments || []);
  const [isUploading, setIsUploading] = useState(false);

  // Automatically generated keywords and tags based on entered data
  const autoGeneratedKeywords = useMemo(() => {
    const tags = new Set<string>();
    
    // Add category tags
    const catStr = String(category).toUpperCase();
    if (catStr === "PLAN" || catStr.includes("PLAN")) {
      tags.add("plan");
      tags.add("architectural");
      tags.add("2d cad");
    } else if (catStr === "3D" || catStr.includes("3D") || catStr.includes("ELEVATION")) {
      tags.add("3d");
      tags.add("elevation");
      tags.add("render");
    } else if (catStr === "ESTIMATE" || catStr.includes("ESTIMATE") || catStr.includes("BOQ")) {
      tags.add("estimate");
      tags.add("boq");
      tags.add("costing");
    } else if (catStr === "SURVEY" || catStr.includes("SURVEY") || catStr.includes("FMB")) {
      tags.add("survey");
      tags.add("fmb");
      tags.add("land plot");
    } else if (catStr === "DOCUMENTS" || catStr.includes("DOCUMENT") || catStr.includes("OFFICE") || catStr.includes("PERMIT")) {
      tags.add("documents");
      tags.add("permit");
      tags.add("office file");
    }

    // Owner / Client Name
    if (ownerName.trim()) {
      tags.add(ownerName.trim().toLowerCase());
      ownerName.trim().toLowerCase().split(/\s+/).forEach((w) => {
        if (w.length >= 3) tags.add(w);
      });
    }

    // File name
    if (name.trim()) {
      const cleanName = name.replace(/\.[^/.]+$/, "").replace(/[_-]/g, " ").toLowerCase();
      cleanName.split(/\s+/).forEach((w) => {
        if (w.length >= 3) tags.add(w);
      });
    }

    // Facing
    if (facing) {
      if (facing.includes("East")) tags.add("east-facing");
      if (facing.includes("West")) tags.add("west-facing");
      if (facing.includes("North")) tags.add("north-facing");
      if (facing.includes("South")) tags.add("south-facing");
    }

    // Bedrooms
    if (bedrooms) {
      const bhkClean = bedrooms.toLowerCase().replace(/\s+/g, "");
      if (bhkClean.includes("bhk")) tags.add(bhkClean);
    }

    // Floors
    if (floors) {
      if (floors.includes("Single")) tags.add("single-floor");
      if (floors.includes("G + 1") || floors.includes("2 Floors")) tags.add("g+1");
      if (floors.includes("G + 2") || floors.includes("3 Floors")) tags.add("g+2");
    }

    // Built-up Area
    if (builtUpArea.trim()) {
      const numMatch = builtUpArea.match(/\d+/);
      if (numMatch) tags.add(`${numMatch[0]}sqft`);
    }

    // Vasthu Chuttu
    if (vasthuChuttu.trim()) {
      tags.add("vasthu");
      if (vasthuChuttu.toLowerCase().includes("dhana")) tags.add("dhana-porutham");
    }

    // Location
    if (location.trim()) {
      location.trim().toLowerCase().split(/[, ]+/).forEach((loc) => {
        if (loc.length >= 3) tags.add(loc);
      });
    }

    // Folder
    const activeF = folders.find((f) => f.id === folderId);
    if (activeF) {
      tags.add(activeF.name.toLowerCase());
    }

    // File extensions
    attachments.forEach((att) => {
      const ext = att.name.split(".").pop()?.toLowerCase();
      if (ext) tags.add(ext);
    });
    if (name.includes(".")) {
      const ext = name.split(".").pop()?.toLowerCase();
      if (ext) tags.add(ext);
    }

    return Array.from(tags).filter(Boolean);
  }, [category, ownerName, name, facing, bedrooms, floors, builtUpArea, vasthuChuttu, location, folderId, folders, attachments]);

  if (!isOpen) return null;

  // Handle Multi-File Upload with base64 conversion
  const handleFileUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const uploadedFiles = e.target.files;
    if (!uploadedFiles || uploadedFiles.length === 0) return;

    setIsUploading(true);

    Array.from(uploadedFiles).forEach((uploadedFile: File) => {
      const isDwg = uploadedFile.name.toLowerCase().endsWith(".dwg");
      const isDxf = uploadedFile.name.toLowerCase().endsWith(".dxf");
      const isPdf = uploadedFile.name.toLowerCase().endsWith(".pdf");
      const isImg = /\.(png|jpe?g|webp|svg)$/i.test(uploadedFile.name);
      const ext = uploadedFile.name.split(".").pop()?.toUpperCase() || "FILE";

      // Auto-populate name if empty
      if (!name) {
        setName(uploadedFile.name);
      }

      if (isDwg) setFileType("DWG");
      else if (isDxf) setFileType("DXF");
      else if (isPdf) setFileType("PDF");
      else if (isImg) setFileType("IMAGE");

      const reader = new FileReader();
      reader.onload = (event) => {
        const dataUrl = event.target?.result as string;
        const newAtt: CADAttachment = {
          id: `att-${Date.now()}-${Math.random().toString(36).substr(2, 5)}`,
          name: uploadedFile.name,
          type: uploadedFile.type || `application/${ext.toLowerCase()}`,
          size: uploadedFile.size,
          dataUrl,
          uploadedAt: new Date().toISOString(),
          isDwgOrDxf: isDwg || isDxf,
          isPdf,
          isImage: isImg
        };

        setAttachments((prev) => [...prev, newAtt]);
        setIsUploading(false);
      };

      reader.onerror = () => {
        setIsUploading(false);
      };

      reader.readAsDataURL(uploadedFile);
    });

    if (fileInputRef.current) fileInputRef.current.value = "";
  };

  const handleRemoveAttachment = (attId: string) => {
    setAttachments(attachments.filter((a) => a.id !== attId));
  };

  // Form Submit
  const handleSave = (e: React.FormEvent) => {
    e.preventDefault();

    const selectedFolder = folders.find((f) => f.id === folderId) || folders[0];
    const totalSize = attachments.reduce((sum, a) => sum + a.size, 0) || file?.fileSize || 1500000;

    // Determine file type automatically
    let resolvedFileType: CADFileType = fileType;
    if (attachments.length > 0) {
      if (attachments.some((a) => a.name.toLowerCase().endsWith(".dwg"))) resolvedFileType = "DWG";
      else if (attachments.some((a) => a.name.toLowerCase().endsWith(".dxf"))) resolvedFileType = "DXF";
      else if (attachments.some((a) => a.isPdf)) resolvedFileType = "PDF";
      else if (attachments.some((a) => a.isImage)) resolvedFileType = "IMAGE";
      else resolvedFileType = "DOC";
    } else if (name.toLowerCase().endsWith(".dwg")) {
      resolvedFileType = "DWG";
    } else if (name.toLowerCase().endsWith(".dxf")) {
      resolvedFileType = "DXF";
    } else if (name.toLowerCase().endsWith(".pdf")) {
      resolvedFileType = "PDF";
    } else if (/\.(png|jpe?g|webp)$/i.test(name)) {
      resolvedFileType = "IMAGE";
    } else {
      if (category === "PLAN") resolvedFileType = "DWG";
      else if (category === "3D") resolvedFileType = "IMAGE";
      else if (category === "ESTIMATE") resolvedFileType = "DOC";
      else if (category === "SURVEY") resolvedFileType = "DWG";
      else resolvedFileType = "PDF";
    }

    const savedRecord: CADDrawingRecord = {
      id: file?.id || `CAD-${new Date().getFullYear()}-${String(Math.floor(Math.random() * 900) + 100).padStart(3, "0")}`,
      name: name.trim() || "Untitled_Drawing.dwg",
      title: name.trim() || "Untitled Drawing",
      folderId: selectedFolder ? selectedFolder.id : "folder-deepak",
      folderPath: selectedFolder ? selectedFolder.path : "/DEEPAK",
      projectCode: projectCode.trim() || `PRJ-${new Date().getFullYear()}-${Math.floor(Math.random() * 90) + 10}`,
      projectName: ownerName.trim() ? `${ownerName.trim()} Residence` : (name.trim() || "Vasthusilpy Project"),
      ownerName: ownerName.trim(),
      clientName: ownerName.trim(),
      mobileNo: mobileNo.trim(),
      clientPhone: mobileNo.trim(),
      facing,
      bedrooms,
      floors,
      vasthuChuttu: vasthuChuttu.trim(),
      plotArea: "",
      builtUpArea: builtUpArea.trim(),
      location: location.trim(),
      category,
      fileType: resolvedFileType,
      fileSize: totalSize,
      keywords: autoGeneratedKeywords,
      description: description.trim(),
      notes: "",
      attachments,
      drawingData: file?.drawingData || {
        version: "1.0",
        units: "meters",
        scale: 1,
        layers: [
          { id: "layer-walls", name: "01_WALLS", color: "#10b981", visible: true, locked: false },
          { id: "layer-doors", name: "02_DOORS_WINDOWS", color: "#06b6d4", visible: true, locked: false },
          { id: "layer-dims", name: "03_DIMENSIONS", color: "#f59e0b", visible: true, locked: false },
          { id: "layer-vastu", name: "04_VASTU_MANDALA", color: "#ec4899", visible: true, locked: false },
          { id: "layer-text", name: "05_ANNOTATIONS", color: "#e2e8f0", visible: true, locked: false }
        ],
        entities: [
          { id: "w-1", type: "rect", layer: "layer-walls", x: 2, y: 2, width: 14, height: 11, strokeWidth: 3, color: "#10b981" },
          { id: "v-1", type: "vastu_grid", layer: "layer-vastu", x: 2, y: 2, width: 14, height: 11, color: "#ec4899" },
          { id: "t-1", type: "text", layer: "layer-text", x: 3.5, y: 4.5, text: `${name || "RESIDENCE"} PLAN`, fontSize: 15, color: "#38bdf8" }
        ]
      },
      shareSettings: file?.shareSettings || {
        isShared: true,
        shareToken: `vst-${Math.random().toString(36).substr(2, 9)}`,
        allowDownload: true,
        allowEdit: false
      },
      googleDriveSyncedAt: file?.googleDriveSyncedAt,
      createdAt: file?.createdAt || new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      createdBy: file?.createdBy || userEmail,
      version: (file?.version || 0) + 1,
      isStarred
    };

    saveCADDrawingRecord(savedRecord);
    onSaved(savedRecord);
    onClose();
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/85 backdrop-blur-md p-3 sm:p-5 overflow-y-auto">
      <div className="bg-slate-900 border border-slate-700/80 rounded-2xl shadow-2xl w-full max-w-4xl overflow-hidden flex flex-col my-auto animate-in fade-in zoom-in-95 duration-200 max-h-[92vh]">
        {/* Header */}
        <div className="bg-slate-950 border-b border-slate-800 px-6 py-4 flex items-center justify-between shrink-0">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-cyan-950 border border-cyan-700 flex items-center justify-center text-cyan-400">
              {file ? <FileCode className="w-5 h-5" /> : <Plus className="w-5 h-5" />}
            </div>
            <div>
              <h3 className="text-base sm:text-lg font-bold text-white font-mono">
                {file ? "Edit Drawing Record & Metadata" : "Add / Upload New Drawing to Vault"}
              </h3>
              <p className="text-xs text-slate-400">
                Attach CAD (DWG/DXF), PDF & 3D Image drawings with comprehensive search specs
              </p>
            </div>
          </div>

          <button
            onClick={onClose}
            className="p-1.5 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-400 hover:text-white transition-colors cursor-pointer"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Form Body */}
        <form onSubmit={handleSave} className="flex-1 overflow-y-auto p-6 space-y-6">
          {/* Target Folder & Category */}
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 p-4 rounded-2xl bg-slate-950/80 border border-slate-800">
            <div>
              <label className="block text-xs font-mono font-bold text-cyan-300 mb-1.5 flex items-center gap-1.5">
                <Folder className="w-3.5 h-3.5" />
                Target Vault Folder <span className="text-rose-400">*</span>
              </label>
              <select
                value={folderId}
                onChange={(e) => setFolderId(e.target.value)}
                className="w-full bg-slate-900 border border-slate-700 rounded-xl px-3 py-2 text-xs text-white focus:outline-none focus:border-cyan-500 font-mono"
              >
                {folders.map((f) => (
                  <option key={f.id} value={f.id}>
                    📁 {f.path} ({f.name})
                  </option>
                ))}
              </select>
            </div>

            <div>
              <label className="block text-xs font-mono font-bold text-slate-300 mb-1.5">
                Category
              </label>
              <select
                value={category}
                onChange={(e) => setCategory(e.target.value as CADCategory)}
                className="w-full bg-slate-900 border border-slate-700 rounded-xl px-3 py-2 text-xs text-slate-200 focus:outline-none focus:border-cyan-500 font-mono"
              >
                {CATEGORIES.map((cat) => (
                  <option key={cat.value} value={cat.value}>
                    {cat.label} ({cat.labelMl})
                  </option>
                ))}
              </select>
            </div>
          </div>

          {/* Drawing File Name */}
          <div>
            <label className="block text-xs font-mono font-bold text-slate-300 mb-1.5">
              Drawing File Name <span className="text-rose-400">*</span>
            </label>
            <input
              type="text"
              required
              value={name}
              onChange={(e) => setName(e.target.value)}
              placeholder="e.g. Keralassery_3BHK_GroundFloor_Vastu.dwg"
              className="w-full bg-slate-950 border border-slate-700 rounded-xl px-3.5 py-2.5 text-xs text-white placeholder-slate-500 focus:outline-none focus:border-cyan-500 font-mono"
            />
          </div>

          {/* Owner & Mobile */}
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <div>
              <label className="block text-xs font-mono font-bold text-slate-300 mb-1.5 flex items-center gap-1.5">
                <User className="w-3.5 h-3.5 text-cyan-400" />
                Owner / Client Name <span className="text-rose-400">*</span>
              </label>
              <input
                type="text"
                required
                value={ownerName}
                onChange={(e) => setOwnerName(e.target.value)}
                placeholder="e.g. Santhosh Kumar K."
                className="w-full bg-slate-950 border border-slate-700 rounded-xl px-3.5 py-2.5 text-xs text-white placeholder-slate-500 focus:outline-none focus:border-cyan-500 font-mono"
              />
            </div>

            <div>
              <label className="block text-xs font-mono font-bold text-slate-300 mb-1.5 flex items-center gap-1.5">
                <Phone className="w-3.5 h-3.5 text-emerald-400" />
                Mobile Number
              </label>
              <input
                type="text"
                value={mobileNo}
                onChange={(e) => setMobileNo(e.target.value)}
                placeholder="e.g. +91 9447123456"
                className="w-full bg-slate-950 border border-slate-700 rounded-xl px-3.5 py-2.5 text-xs text-white placeholder-slate-500 focus:outline-none focus:border-cyan-500 font-mono"
              />
            </div>
          </div>

          {/* Architectural Specs: Facing, Bedrooms, Floors, Vasthu Chuttu, Plinth */}
          <div className="p-4 rounded-2xl bg-slate-950/90 border border-slate-800 space-y-4">
            <div className="text-xs font-mono font-bold text-cyan-400 flex items-center gap-1.5 uppercase tracking-wider">
              <Compass className="w-4 h-4" />
              Architectural & Vasthu Specifications (Searchable)
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
              <div>
                <label className="block text-xs font-mono font-bold text-slate-300 mb-1.5">
                  Building Facing (ദിശ)
                </label>
                <select
                  value={facing}
                  onChange={(e) => setFacing(e.target.value)}
                  className="w-full bg-slate-900 border border-slate-700 rounded-xl px-3 py-2 text-xs text-amber-300 focus:outline-none focus:border-cyan-500 font-mono"
                >
                  {FACING_OPTIONS.map((f) => (
                    <option key={f} value={f}>
                      {f}
                    </option>
                  ))}
                </select>
              </div>

              <div>
                <label className="block text-xs font-mono font-bold text-slate-300 mb-1.5">
                  Number of Bedrooms
                </label>
                <select
                  value={bedrooms}
                  onChange={(e) => setBedrooms(e.target.value)}
                  className="w-full bg-slate-900 border border-slate-700 rounded-xl px-3 py-2 text-xs text-cyan-300 focus:outline-none focus:border-cyan-500 font-mono"
                >
                  {BEDROOM_OPTIONS.map((b) => (
                    <option key={b} value={b}>
                      {b}
                    </option>
                  ))}
                </select>
              </div>

              <div>
                <label className="block text-xs font-mono font-bold text-slate-300 mb-1.5">
                  Number of Floors
                </label>
                <select
                  value={floors}
                  onChange={(e) => setFloors(e.target.value)}
                  className="w-full bg-slate-900 border border-slate-700 rounded-xl px-3 py-2 text-xs text-purple-300 focus:outline-none focus:border-cyan-500 font-mono"
                >
                  {FLOOR_OPTIONS.map((fl) => (
                    <option key={fl} value={fl}>
                      {fl}
                    </option>
                  ))}
                </select>
              </div>
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              <div>
                <label className="block text-xs font-mono font-bold text-slate-300 mb-1.5">
                  വാസ്തു ചുറ്റ് (Vasthu Chuttu)
                </label>
                <input
                  type="text"
                  value={vasthuChuttu}
                  onChange={(e) => setVasthuChuttu(e.target.value)}
                  placeholder="e.g. 43 Kol 16 Viral (Dhana Porutham)"
                  className="w-full bg-slate-900 border border-slate-700 rounded-xl px-3 py-2 text-xs text-amber-200 font-mono focus:outline-none focus:border-amber-500"
                />
              </div>

              <div>
                <label className="block text-xs font-mono font-bold text-slate-300 mb-1.5">
                  Plinth / Built-up Area
                </label>
                <input
                  type="text"
                  value={builtUpArea}
                  onChange={(e) => setBuiltUpArea(e.target.value)}
                  placeholder="e.g. 1680 Sq.Ft (156 Sq.M)"
                  className="w-full bg-slate-900 border border-slate-700 rounded-xl px-3 py-2 text-xs text-emerald-300 font-mono focus:outline-none focus:border-cyan-500"
                />
              </div>
            </div>
          </div>

          {/* Location & Project Code */}
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <div>
              <label className="block text-xs font-mono font-bold text-slate-300 mb-1.5 flex items-center gap-1.5">
                <MapPin className="w-3.5 h-3.5 text-rose-400" />
                Project Location
              </label>
              <input
                type="text"
                value={location}
                onChange={(e) => setLocation(e.target.value)}
                placeholder="e.g. Keralassery, Palakkad"
                className="w-full bg-slate-950 border border-slate-700 rounded-xl px-3.5 py-2 text-xs text-white placeholder-slate-500 focus:outline-none focus:border-cyan-500 font-mono"
              />
            </div>

            <div>
              <label className="block text-xs font-mono font-bold text-slate-300 mb-1.5">
                Project Code / Reference
              </label>
              <input
                type="text"
                value={projectCode}
                onChange={(e) => setProjectCode(e.target.value)}
                placeholder="e.g. PRJ-2026-042"
                className="w-full bg-slate-950 border border-slate-700 rounded-xl px-3.5 py-2 text-xs text-white placeholder-slate-500 focus:outline-none focus:border-cyan-500 font-mono"
              />
            </div>
          </div>

          {/* File Attachments (PDF, DWG, DXF, Images) */}
          <div className="p-4 rounded-2xl bg-slate-950/90 border border-slate-800 space-y-3">
            <div className="flex items-center justify-between">
              <label className="text-xs font-mono font-bold text-cyan-300 flex items-center gap-2">
                <Paperclip className="w-4 h-4" />
                Attached Files (PDF, DWG, DXF, Images, CAD)
              </label>
              <span className="text-[11px] text-slate-400 font-mono">
                {attachments.length} file{attachments.length !== 1 ? "s" : ""} attached
              </span>
            </div>

            {/* Drag & Drop Upload Zone */}
            <div
              onClick={() => fileInputRef.current?.click()}
              className="border-2 border-dashed border-slate-700 hover:border-cyan-500/80 rounded-xl p-5 text-center cursor-pointer transition-colors bg-slate-900/50 hover:bg-slate-900 group"
            >
              <Upload className="w-7 h-7 text-slate-400 group-hover:text-cyan-400 mx-auto mb-2 transition-colors" />
              <div className="text-xs font-bold text-slate-200 font-mono">
                Click to browse or drag & drop files here
              </div>
              <div className="text-[11px] text-slate-400 mt-1">
                Supports AutoCAD (.dwg, .dxf), Drawings (.pdf), 3D Renders (.png, .jpg, .webp), and Docs
              </div>
              <input
                ref={fileInputRef}
                type="file"
                multiple
                accept=".dwg,.dxf,.pdf,.png,.jpg,.jpeg,.webp,.svg,.doc,.docx"
                onChange={handleFileUpload}
                className="hidden"
              />
            </div>

            {/* Attachments List */}
            {attachments.length > 0 && (
              <div className="space-y-2 pt-2">
                {attachments.map((att) => (
                  <div
                    key={att.id}
                    className="flex items-center justify-between p-3 rounded-xl bg-slate-900 border border-slate-800 text-xs font-mono"
                  >
                    <div className="flex items-center gap-3 min-w-0">
                      {att.isPdf ? (
                        <FileText className="w-4 h-4 text-rose-400 shrink-0" />
                      ) : att.isImage ? (
                        <Sparkles className="w-4 h-4 text-amber-400 shrink-0" />
                      ) : (
                        <FileCode className="w-4 h-4 text-cyan-400 shrink-0" />
                      )}
                      <div className="min-w-0">
                        <div className="text-white font-bold truncate">{att.name}</div>
                        <div className="text-[10px] text-slate-400">{formatBytes(att.size)}</div>
                      </div>
                    </div>

                    <button
                      type="button"
                      onClick={() => handleRemoveAttachment(att.id)}
                      className="p-1.5 rounded-lg bg-slate-800 hover:bg-rose-500/20 text-slate-400 hover:text-rose-400 transition-colors cursor-pointer"
                    >
                      <Trash2 className="w-4 h-4" />
                    </button>
                  </div>
                ))}
              </div>
            )}
          </div>

          {/* Automatically Generated Keywords & Tags */}
          <div className="p-4 rounded-2xl bg-slate-950/80 border border-slate-800 space-y-2">
            <div className="flex items-center justify-between">
              <label className="text-xs font-mono font-bold text-cyan-300 flex items-center gap-1.5">
                <Tag className="w-3.5 h-3.5 text-cyan-400" />
                Auto-Generated Keywords & Search Tags
              </label>
              <span className="text-[10px] font-mono text-slate-400 bg-slate-900 px-2 py-0.5 rounded-full border border-slate-800">
                {autoGeneratedKeywords.length} tags derived
              </span>
            </div>
            <p className="text-[11px] text-slate-400 font-mono">
              Tags are automatically added in real-time based on Client, Category, Facing, BHK, Floors, Vasthu, Location & Files:
            </p>

            {/* Keyword Badges */}
            <div className="flex flex-wrap gap-1.5 pt-1">
              {autoGeneratedKeywords.map((kw) => (
                <span
                  key={kw}
                  className="inline-flex items-center gap-1 px-2.5 py-1 rounded-lg bg-cyan-950/70 border border-cyan-700/50 text-cyan-300 text-[11px] font-mono shadow-sm"
                >
                  #{kw}
                </span>
              ))}
              {autoGeneratedKeywords.length === 0 && (
                <span className="text-xs text-slate-500 font-mono italic">
                  Enter drawing details above to generate search tags automatically.
                </span>
              )}
            </div>
          </div>

          {/* Description */}
          <div>
            <label className="block text-xs font-mono font-bold text-slate-300 mb-1.5">
              Description / Scope
            </label>
            <textarea
              rows={3}
              value={description}
              onChange={(e) => setDescription(e.target.value)}
              placeholder="Details of the architectural drawing, room dimensions, Vastu specifications, submission details..."
              className="w-full bg-slate-950 border border-slate-700 rounded-xl p-3 text-xs text-white placeholder-slate-500 focus:outline-none focus:border-cyan-500 font-mono"
            />
          </div>

          {/* Starred Checkbox */}
          <div className="flex items-center gap-2">
            <input
              type="checkbox"
              id="isStarred"
              checked={isStarred}
              onChange={(e) => setIsStarred(e.target.checked)}
              className="rounded bg-slate-800 border-slate-700 text-amber-500 focus:ring-0 cursor-pointer"
            />
            <label
              htmlFor="isStarred"
              className="text-xs font-mono text-slate-300 flex items-center gap-1.5 cursor-pointer"
            >
              <Star className="w-3.5 h-3.5 text-amber-400" />
              Mark as Starred / Priority Project
            </label>
          </div>

          {/* Footer Actions */}
          <div className="pt-4 border-t border-slate-800 flex items-center justify-between gap-3 shrink-0">
            {file && onDelete ? (
              <button
                type="button"
                onClick={() => {
                  if (confirm(`Are you sure you want to permanently delete "${file.name}"?`)) {
                    onDelete(file.id);
                    onClose();
                  }
                }}
                className="px-4 py-2.5 rounded-xl bg-rose-950/60 hover:bg-rose-600 text-rose-300 hover:text-white border border-rose-800/80 text-xs font-mono font-bold flex items-center gap-1.5 cursor-pointer transition-all"
              >
                <Trash2 className="w-4 h-4" />
                <span>Delete Drawing</span>
              </button>
            ) : (
              <div />
            )}

            <div className="flex items-center gap-3">
              <button
                type="button"
                onClick={onClose}
                className="px-4 py-2.5 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-300 text-xs font-mono font-bold cursor-pointer transition-colors"
              >
                Cancel
              </button>
              <button
                type="submit"
                className="px-6 py-2.5 rounded-xl bg-gradient-to-r from-cyan-600 to-blue-600 hover:from-cyan-500 hover:to-blue-500 text-white text-xs font-mono font-bold flex items-center gap-2 shadow-lg shadow-cyan-950 cursor-pointer transition-all"
              >
                <Save className="w-4 h-4" />
                <span>{file ? "Update Drawing" : "Save to Vault"}</span>
              </button>
            </div>
          </div>
        </form>
      </div>
    </div>
  );
};
